# Generated by Django 4.1.5 on 2023-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demoapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=4000)),
                ('status', models.BooleanField(default=False)),
                ('contributor', models.CharField(max_length=15)),
            ],
        ),
    ]
